# Generated by Django 2.2.4 on 2019-12-20 20:12

from django.db import migrations, models
import djongo.models.fields
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h1', models.CharField(max_length=100)),
                ('content', djongo.models.fields.EmbeddedModelField(model_container=myapp.models.SearchByActors, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actors', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('movieNames', models.CharField(max_length=100)),
                ('rating', models.CharField(max_length=100)),
                ('directors', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='SearchByActor',
        ),
        migrations.DeleteModel(
            name='SearchByDirector',
        ),
        migrations.DeleteModel(
            name='SearchByGenre',
        ),
        migrations.DeleteModel(
            name='SearchByName',
        ),
        migrations.DeleteModel(
            name='SearchByRating',
        ),
    ]
