# Generated by Django 2.2.4 on 2019-12-26 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20191226_1238'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Search',
        ),
    ]
