# Generated by Django 2.2.4 on 2019-12-26 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20191220_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchByActors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actors', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SearchByDirectors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directors', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SearchByGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SearchByMovieName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieNames', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SearchByRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.RemoveField(
            model_name='search',
            name='actors',
        ),
        migrations.RemoveField(
            model_name='search',
            name='directors',
        ),
        migrations.RemoveField(
            model_name='search',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='search',
            name='movieNames',
        ),
        migrations.RemoveField(
            model_name='search',
            name='rating',
        ),
    ]
