# Generated by Django 2.2.4 on 2019-12-26 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_delete_search'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchbyactors',
            options={'verbose_name_plural': 'Searches By Actors'},
        ),
        migrations.AlterModelOptions(
            name='searchbydirectors',
            options={'verbose_name_plural': 'Searches By Directors'},
        ),
        migrations.AlterModelOptions(
            name='searchbygenre',
            options={'verbose_name_plural': 'Searches By Genres'},
        ),
        migrations.AlterModelOptions(
            name='searchbymoviename',
            options={'verbose_name_plural': 'Searches By Movie Names'},
        ),
        migrations.AlterModelOptions(
            name='searchbyrating',
            options={'verbose_name_plural': 'Searches By Rating'},
        ),
    ]
